### ISSUE TITLE
normalizedPdp

### ISSUE THREAD

**Issue by liuqipei** [MetalKnight/woss-ns3#10]
Thank you for your wonderful work, but I can't find a definition about method _normalizedPdp()_ in class **UanPdb** along with its implement,would you like to make it clear?

**Comment by MetalKnight** [comment]
Hi there, thanks! :smile: 
@liuqipei 
regarding your request, are you referring to line 213 of woss-channel.cpp ?

`UanPdp normalizedPdp = j->NormalizeToSumNc ();`

**Comment by MetalKnight** [comment]
@liuqipei it seems that UAN wasn't properly patched.
we will do that ASAP.
thanks for spotting it out.

**Comment by MetalKnight** [comment]
UAN issue tracked here.

https://www.nsnam.org/bugzilla/show_bug.cgi?id=2299

**Comment by MetalKnight** [comment]
Patch has been cleared for merging.
Issue will be closed after that.

**Comment by MetalKnight** [comment]
UAN has been properly patched.
check official dev repository
