### ISSUE TITLE
Make woss-ns3 compatible with CMake build system

### ISSUE THREAD

**Issue by MetalKnight** [MetalKnight/woss-ns3#35]
CMake will be shortly introduced into ns-3. WOSS should be made compatible with the new build system

**Comment by Gabrielcarvfer** [comment]
@MetalKnight do you prefer the script to reproduce exactly the waf behavior or can I change it to automatically fetch sources and build WOSS?

**Comment by MetalKnight** [comment]
@Gabrielcarvfer I would stick with exact waf behavior since automatically fetch and build, would be very hard to automatically do (many libraries, which might require manual step for install)

**Comment by MetalKnight** [comment]
@Gabrielcarvfer would please provide some configuration syntax example?
thanks again!
